### PR TITLE
Return Service Information from Base Endpoint

### PR DESCRIPTION
**Pull request by ChungLinWu0829**
### Description:
Return Service Information from Base Endpoint

### Test result:
image

### Story reference: 
https://app.zenhub.com/workspaces/promotions-su24-001-666234565dda150276ad19c5/issues/gh/csci-ga-2820-su24-001/promotions/12

### CODE REVIEW

**Comment by mingyi850** [comment]
Hey @ChungLinWu0829 , looks good, can we just add a test case for coverage - can be merged once done

**Comment by ChungLinWu0829** [comment]
> Hey @ChungLinWu0829 , looks good, can we just add a test case for coverage - can be merged once done

Hi @mingyi850, thanks for the quick review. I noticed that adding a test case for the section that returns a JSON file doesn't impact the coverage metrics. I tried adding a test case, but the coverage did not change. Do we still need that?
image

**Comment by mingyi850** [comment]
Oh sorry i didn't realise there was already a text_index - i think it's fine then!

**Review by mingyi850 — APPROVED** [review]
LGTM

**Pull request merged**
